Traceback (most recent call last):
  File "e:\LEARNING PYTHON\AUTOMATE THE BORING STUFF\10. DEBUGGING\GettingTheTracebackAsAString.py", line 36, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
